# Generated by Django 4.1.7 on 2023-03-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('mail', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('rand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=1)),
                ('role_number', models.PositiveIntegerField()),
                ('difficulty', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('grade', models.FloatField()),
                ('time', models.FloatField()),
            ],
            options={
                'unique_together': {('classroom', 'role_number', 'difficulty', 'level', 'date')},
            },
        ),
    ]
