# Generated by Django 4.1.7 on 2023-05-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoonicWebsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recovers',
        ),
    ]
